### PR TITLE
improved alt text and colors for better readability

### PR DESCRIPTION
**Pull request by TheDarkLord247**
Previous blue:
Screen Shot 2022-02-28 at 6 57 39 PM

New blue:
Screen Shot 2022-02-28 at 6 57 25 PM

Previous feature map demo:
Screen Shot 2022-02-28 at 7 11 42 PM

New feature map demo:
Screen Shot 2022-02-28 at 7 11 16 PM

### CODE REVIEW

**Comment by TheDarkLord247** [comment]
the alt text tester doesn't like me using the word 'image' in the alt texts but its actually important to describe convolutions, etc. 💀 do you know how I can silence these? @doubleiis02  Ig we don't need to pass this test...

**Review by doubleiis02 — CHANGES_REQUESTED** [review]
The top of `components/Carousel.js` contains this line: `/* eslint-disable jsx-a11y/img-redundant-alt */`
Says that you added this line a year ago lol. I think you just add this line to all the other files that cause the error.

**Comment by TheDarkLord247** [comment]
fixed

**Comment by TheDarkLord247** [comment]
oh wait package-lock has 17k new lines - is there any way we can avoid this?

**Review by doubleiis02 — APPROVED** [review]
o7

**Pull request merged**
