### PR TITLE
Flashlight

### PR DESCRIPTION
**Pull request by mayaraman19**
omg attempted to incorporate REFS into the flashlight 😳 still using `getBoundingClientRect()`, but I think that was okay. Avoids use of `document.getElementById()`. used [this link](https://medium.com/@rossbulat/how-to-use-react-refs-4541a7501663) as reference!

### CODE REVIEW

**Comment by mayaraman19** [comment]
this stupid commit history i've literally deleted my branches 400 times why cant i get rid of it

**Comment by malsf21** [comment]
> this stupid commit history i've literally deleted my branches 400 times why cant i get rid of it

Hm yeah I'm not sure tbh, have you been making your new branches from up-to-date master and stuff?

Also do you want me to review 👀 ? Honestly I think it's prob good to merge

**Comment by malsf21** [comment]
> Is it worth looking into replacing the CSS-in-JS with refs instead?

Nah, I think it's good as is - this is probably (?) the correct way to implement changing opacity and stuff.

If you remove all the comments and the empty lifecycle, then I'll give it the OK!

**Review by malsf21 — APPROVED** [review]
Chef's kiss! Sorry this was such a headache :( 

As normal, I'll let you do the ~ honours ~ - you may want to squash merge!

(also once you merge, I suggest maybe nuking your local repo and recloning - maybe it helps with the commit history issues?)

**Pull request merged**
