### PR TITLE
CNN Visualization

### PR DESCRIPTION
**Pull request by NishaMcNealis**
added cnn visualization and other minor content changes

### CODE REVIEW

**Comment by malsf21** [comment]
Hm, something funky has gone on with the file permissions for the pull request, I'm not sure if you've noticed but the file diff is really polluted. Do you mind making a new branch off of `master` (maybe after Maya merges her PR) and copying over the changes there? Super sorry about that!

**Comment by malsf21** [comment]
Oh and also, is the magnifier being used because the image is hard to examine? Or is there another reason?

**Comment by krashanoff** [comment]
> Hm, something funky has gone on with the file permissions for the pull request, I'm not sure if you've noticed but the file diff is really polluted. Do you mind making a new branch off of `master` (maybe after Maya merges her PR) and copying over the changes there? Super sorry about that!

If Nisha is using WSL, there's a strong possibility that the permission bits were gnarled. If not, we can revert the changes with `chmod -R 655 .`.

**Comment by NishaMcNealis** [comment]
@malsf21 ok i'll try a new branch rn! we put in the magnifier because it was kinda hard to see the details on smaller screens but we think it's important to show the whole image at once so people can see how all the elements fit together. if you have any other ideas for how we could do that let us know!

**Comment by NishaMcNealis** [comment]
the new PR is https://github.com/uclaacm/no-filter/pull/16 i'm gonna close this one so there's no confusion

**Pull request closed without merging**
