### PR TITLE
Flashlight

### PR DESCRIPTION
**Pull request by mayaraman19**
Like what Tomoki wrote on [this doc](https://docs.google.com/document/d/1Dh_6WvlQdU28x4M77aN0jo_ygpm1N1WCRYqq140jAx4/edit), I removed the instructions on how to use the flashlight from the side of the 'card' and added it as text on top of the flashlight component instead.

Current concerns/todos:
- Code? I feel like there are better ways to do this??? (using pseudoelements for the background of the flashlight image??????) but I wasn't sure how to do this in CSS-in-JS
- Style of the whole message is a big todo
- and centering the flashlight but i'm too lazy to do that rn
- also checking mobile compatibility

### CODE REVIEW

**Comment by mayaraman19** [comment]
Also i just tried the netflify deployment and it completely glitched and showed the entire koala for 0.5s 😪 will have to check that out

**Comment by malsf21** [comment]
> Also i just tried the netflify deployment and it completely glitched and showed the entire koala for 0.5s 😪 will have to check that out

Hm, I can't replicate this (tried on Chrome, Firefox, and Safari on a Mac) - what did you do to get it to happen?

I'll do a review in a bit! 

(also, Safari is still bugging out for me :/ )

**Review by malsf21 — COMMENTED** [review]
> Code? I feel like there are better ways to do this??? (using pseudoelements for the background of the flashlight image??????) but I wasn't sure how to do this in CSS-in-JS

After giving it a once-over, I'm actually pretty impressed with this approach - even if there is a better way to do this, I'm not sure if anything comes to the top of my head. Bravo 👏 

(there is obv an accessibility concern, but I think to some extent it's unavoidable with the type of demo that this is; I have an idea of what we can do - a button that goes through a predefined set of movements - but we can talk about that later)

> Style of the whole message is a big todo

I'm a fan, though I'm biased because I always like pink! Maybe bolding it for readability, but other than that no complaints. May want to run it through a color contrast checker as well (afaik white on pink is tricky, depends on the shade of pink).

(there's also a funny bug where hovering over where the text would've been changes the cursor style, but I don't think this matters)

> also checking mobile compatibility

Did a quick check on my phone (Chrome/Safari on iOS):

* there's an issue with the scroll-overflow - the convolution-on-car image is too big
* i think the first time you try touching it, I see the koala do the full-flash
* you may want to disable scroll in general while on the element?

Some of these aren't regressions though, so we can always address is later.

Anyways, solid work as always - I think whenever you feel comfortable with this PR, it's probably good to merge (in other words, I don't see anything wrong with it). Thank you for your persistence so far 😊

**Comment by malsf21** [comment]
Going to open/close because Netlify! settings

**Comment by mayaraman19** [comment]
just made the pink instructions bolder and removed the weird cursor behavior + centered the flashlight

Lowkey forgot all my CSS but TODOs are to a) disable scroll action on flashlight i guess and b) fix the way that the koala will Leave the Image ( :( ) if you make the window too small but I'll just do that at a later time but with ur blessing i'll merge this

**Review by malsf21 — APPROVED** [review]
You have my blessing, go for the merge! Just remember to give it the good ol' squash merge.

**Pull request merged**
